<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	  <!--<ApplicationHighDpiMode>DpiUnawareGdiScaled</ApplicationHighDpiMode>-->
	  <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
	  <!--<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GrapeCity.Spread.WinForms.ja" Version="19.0.0" />
  </ItemGroup>

</Project>